# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/troika/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),troika)

$(call add-radio-file-sha1-checked,radio/bootloader.img,bef146887043c45b7b8411927916fad6e53a0b78)
$(call add-radio-file-sha1-checked,radio/keystorage.img,95b526b0f76cbece685da095cbb1c2046bbbd6f9)
$(call add-radio-file-sha1-checked,radio/ldfw.img,597eadf669d4c5a291398142ae7aad4d181e1924)
$(call add-radio-file-sha1-checked,radio/logo.img,5d28da59122b2f87a745f11b4a334586e396bfba)
$(call add-radio-file-sha1-checked,radio/modem.img,bab5df9fa9fb311e5ee7ec3957c172a571feac73)

endif
