# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/troika/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),troika)

$(call add-radio-file-sha1-checked,radio/bootloader.img,33051bd4fa247d809dca0bbc11af50c7a90c8717)
$(call add-radio-file-sha1-checked,radio/keystorage.img,73c3816c898cddc9141757230c106eb856d5d873)
$(call add-radio-file-sha1-checked,radio/ldfw.img,67fd01bf0a2d4ea63c24acc1061a52ce3676c42c)
$(call add-radio-file-sha1-checked,radio/logo.img,5d28da59122b2f87a745f11b4a334586e396bfba)
$(call add-radio-file-sha1-checked,radio/modem.img,b88320e9e08691a6f77e1fe1d3abbe5d0961267f)

endif
